---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.4
  - name: centos-5.9

suites:
 - name: client
   run_list:
   - recipe[nagios::client]
 - name: server
   run_list:
   - recipe[nagios::server]
   attributes:
     roles:
     - monitoring
     nagios:
       additional_contacts:
         root: true
data_bags_path: test/data_bags
roles_path: test/roles

